#!/bin/bash

###########################################################################################
# Author : Rahul Chauhan
#
#
#
#
#
###########################################################################################

# Update EC2 Ubuntu Instance
sudo apt update -y

# Install Docker
sudo apt install docker.io

# Update Ubuntu Instance
sudo apt update -y

# Start docker engine
sudo systemctl start docker

# Grant Access to your user to run docker commands
sudo usermod -aG docker ubuntu
